### ISSUE TITLE
Azure-less scenario

### ISSUE THREAD

**Issue by jariq** [onovotny/SignService#20]
I am considering running SignService as a part of local organization infrastructure (instead of Azure cloud) with PKCS#11 compatible key store (instead of Azure KeyVault) and LDAP compatible directory (instead of Azure AD). Would you be interested in supporting such scenario?

**Comment by onovotny** [comment]
Hi @jariq,

There are really two issues here, so lets split them out:

1. Alternate authentication from Azure AD. Certainly possible. The question would be around making the configuration really simple while maintaining security.

2. Alternate key store. This gets tricky. The service was originally written to use the built-in CNG providers, so if you had a certificate in the local cert store (even if backed by an HSM), it'd work. I removed that in favor of Key Vault as most people don't have custom CNG implementations and the goal here was to make it easy while being secure. If everything you need is available via CNG, then it could be possible to bring back that support, but I hesitate to make it "too easy" for people just to put a code-signing certificate on their web server without a hardware device present.

I'm curious as to the goal here, what is it you're trying to achieve? Even an on-prem server can access Key Vault. A code signing service cannot truly be disconnected from the internet since it must be able to reach timestamp servers as well. Key Vault's HSM is very inexpensive for this use case ($1/mo for a hardware key, and this use pattern won't incur much in the way of per-operation costs).

As soon as you have Key Vault, then you do need AAD in the picture for security. An upcoming feature I'm working on is using the on-behalf-of flow to ensure that the Key Vault is secured to require the incoming user principal + service principal, so that someone operating the service alone cannot access the keys.

**Comment by jariq** [comment]
> I'm curious as to the goal here, what is it you're trying to achieve?

My code signing certificate and private key are both stored on a smartcard and I need to share them with multiple systems and user accounts.

Card comes with minidriver and PKCS#11 library. I've tested it via CSP and PKCS#11 APIs but after reading your answer I'll check whether it can be used via CNG API.

> A code signing service cannot truly be disconnected from the internet since it must be able to reach timestamp servers as well. Key Vault's HSM is very inexpensive for this use case...

Internet connectivity and costs do not really pose a problem in this case. Some people/orgs simply prefer to keep their keys within their physical reach.

**Comment by onovotny** [comment]
I'm going to close this for now since the current design is very heavily tied to Azure. 

Thanks
